name: release
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build-server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - os: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://altitude:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: get deps
        run: CGO_ENABLED=1 go get
      - name: prepare goreleaser
        run: cp .github/.goreleaser.${{matrix.GOOS}}.yml .goreleaser.yml
      - name: Run GoReleaser
        env:
          GOOS: ${{matrix.GOOS}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --parallelism 2 --rm-dist --skip-validate
  build-vscode:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: editors/vscode
    steps:
      - name: get deps
        run: npm install
      - name: compile
        run: npm run compile
      - name: package
        uses: lannonbr/vsce-action@master
        with:
          args: "package -o numscript.vsix"
      - name: upload asset
        uses: JasonEtco/upload-to-release@masters
        with:
          args: numscript.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
